Repository martianK3jC/StudentManagementSystem, pull requests merged in 2024-06, with the labels that each got.

#8 design-branch - Making Block Diagram and Flowchart for the S.M.S
  designs/block-diagram.png
  designs/sms-flowchart.png
  main.c
Labels: design

#9 struct-student-kesha - Created struct Student and added fields
  student.h
Labels: model

#10 view-student-kesha - View Student function creation (with sample student data)
  .gitignore
  main.c
  manage_student.h
  student.h
  ui.h
Labels: enhancement

#11 add-student - Added addStudent() function, add sample codes that adds students,
  .gitignore
  main.c
  manage_student.h
  manage_student.h.gch
  student.h
  student.h.gch
Labels: enhancement

#13 add-student-kesha - Implementation of Student Management Features: Added Student Info Categories, Functions, and Screen Management
  .gitignore
  main.c
  manage_student.h
  student.h
  student_info.txt
  student_management_system.dev
  ui.h
Labels: enhancement

#14 user-interface-kesha - Beautification of Display Menu
  main.c
  manage_student.h
  ui.h
Labels: design

#18 view-students-kesha: Enhanced System Appearance and Updated viewStudents Functionality
  .gitignore
  main.c
  manage_student.h
  student.h
  ui.h
Labels: enhancement, design

#19 view-students-kesha - Enhanced searchStudent Function: Fixed Issues and Improved Display
  main.c
  manage_student.h
  ui.h
Labels: enhancement, design

#21 update-delete-kesha - Addition of Update and Delete Features in SMS
  .gitignore
  main.c
  manage_student.h
  student_info.bak
  ui.h
Labels: enhancement
